# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseworkIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CourseworkIOS

 pod 'Firebase/Analytics'
 pod 'Firebase/Auth'
 pod 'Firebase/Core'
 pod 'Firebase/Firestore'
 pod 'Firebase/Storage'
 pod 'Firebase/Database'
 pod 'SwiftyJSON'
 pod 'Alamofire', '~> 4.4'
 pod 'AlamofireImage', '~> 3.1'

  target 'CourseworkIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
